### ISSUE TITLE
Replace the "wikipedia" dependency for the mediawiki API

### ISSUE THREAD

**Issue by NeoMahler** [Worldev/Searcher#2]
I suggest to use the MediaWiki API to search and read content from Wikipedia, because the wikipedia module is not installed with default Python installations. This would be easier for non-programming people in my opinion!

I can help with the API implementation if needed :)

**Comment by mikicat** [comment]
That'd be great.

**Comment by NeoMahler** [comment]
Ok, I will try to do it when I have time.

**Comment by mikicat** [comment]
Don't worry, I am doing it right now, although I won't finish quickly

**Comment by NeoMahler** [comment]
Oh, ok. But if you need help just ask me. You can also look the Granota wikipedia.py module, which uses json and the urllib (python 2) to query wikipedia.

**Comment by mikicat** [comment]
That's what I'm doing :)
